# Generated by Django 4.0.5 on 2022-06-29 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 30)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
