# Generated by Django 4.0.5 on 2022-06-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='blog.author'),
        ),
    ]
