# Generated by Django 4.0.5 on 2022-07-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(error_messages={'required': 'This field is required'}, max_length=120),
        ),
    ]
